# Generated by Django 4.2.1 on 2023-06-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosContacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=250, verbose_name='Correo')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('mensaje', models.CharField(max_length=100, verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'nombre',
                'verbose_name_plural': 'nombres',
                'ordering': ['id'],
            },
        ),
    ]
