# Generated by Django 4.2.1 on 2023-06-28 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('idArtista', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='idArtista')),
                ('nomArtista', models.CharField(max_length=50, verbose_name='Artista')),
                ('pais', models.CharField(max_length=50, verbose_name='País')),
                ('anio', models.CharField(max_length=4, verbose_name='Año de formación')),
                ('genero', models.CharField(max_length=70, null=True, verbose_name='Género')),
                ('playlist', models.URLField(null=True, verbose_name='Playlist')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ['nomArtista', 'genero'],
            },
        ),
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('idRecinto', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='idRecinto')),
                ('nomRecinto', models.CharField(max_length=80, verbose_name='Recinto')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad')),
                ('comuna', models.CharField(max_length=50, verbose_name='Comuna')),
                ('direccion', models.CharField(max_length=250, verbose_name='Dirección')),
                ('estacionamiento', models.CharField(max_length=3, verbose_name='Estacionamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('idConcierto', models.AutoField(primary_key=True, serialize=False, verbose_name='idConcierto')),
                ('fecha', models.DateTimeField(max_length=60, verbose_name='Fecha')),
                ('valores', models.CharField(max_length=500, verbose_name='Entradas desde')),
                ('venta', models.URLField(max_length=250, null=True, verbose_name='Link de venta')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='concierto', verbose_name='Imagen')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.artista', verbose_name='Artista')),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.recinto', verbose_name='Recinto')),
            ],
            options={
                'verbose_name': 'concierto',
                'verbose_name_plural': 'conciertos',
                'ordering': ['fecha', 'idConcierto'],
            },
        ),
    ]
