# Generated by Django 4.2.1 on 2023-06-26 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('idArtista', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='idArtista')),
                ('nomArtista', models.CharField(max_length=50, verbose_name='Artista')),
                ('origen', models.CharField(max_length=100, verbose_name='Origen')),
                ('anio', models.CharField(max_length=4, verbose_name='Año')),
                ('show', models.CharField(max_length=70, verbose_name='Show')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ['nomArtista'],
            },
        ),
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('idRecinto', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='idRecinto')),
                ('nomRecinto', models.CharField(max_length=80, verbose_name='Recinto')),
                ('capacidad', models.CharField(max_length=10, verbose_name='Capacidad')),
                ('comuna', models.CharField(max_length=50, verbose_name='Comuna')),
                ('direccion', models.CharField(max_length=250, verbose_name='Dirección')),
                ('estacionamiento', models.CharField(max_length=3, verbose_name='Estacionamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('idConcierto', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='idConcierto')),
                ('pais', models.CharField(max_length=30, verbose_name='País')),
                ('fecha', models.CharField(max_length=60, verbose_name='Fecha')),
                ('valores', models.CharField(max_length=500, verbose_name='Valores')),
                ('imagen', models.ImageField(blank=True, height_field=300, null=True, upload_to='concierto', verbose_name='Imagen', width_field=300)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.artista', verbose_name='Artista')),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.recinto', verbose_name='Recinto')),
            ],
            options={
                'verbose_name': 'concierto',
                'verbose_name_plural': 'conciertos',
                'ordering': ['fecha', 'idConcierto'],
            },
        ),
    ]
