# Generated by Django 4.2.1 on 2023-06-26 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='idPais')),
                ('pais', models.CharField(max_length=30, verbose_name='País')),
            ],
            options={
                'ordering': ['idPais', 'pais'],
            },
        ),
        migrations.RemoveField(
            model_name='artista',
            name='origen',
        ),
        migrations.AlterField(
            model_name='recinto',
            name='capacidad',
            field=models.IntegerField(verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='artista',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.pais', verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concierto',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.pais', verbose_name='País'),
        ),
    ]
