# Generated by Django 4.2.1 on 2023-06-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_pais_remove_artista_origen_alter_recinto_capacidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['pais']},
        ),
        migrations.AlterField(
            model_name='pais',
            name='idPais',
            field=models.CharField(default=None, max_length=30, primary_key=True, serialize=False, verbose_name='idPais'),
        ),
    ]
