# Generated by Django 4.2.1 on 2023-06-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_pais_options_alter_pais_idpais'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artista',
            name='pais',
            field=models.CharField(max_length=50, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='concierto',
            name='pais',
            field=models.CharField(max_length=60, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='idPais',
            field=models.CharField(max_length=30, verbose_name='idPais'),
        ),
    ]
