# Generated by Django 4.2.1 on 2023-06-26 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_pais_id_alter_artista_pais_alter_concierto_pais_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
