# Generated by Django 4.2.1 on 2023-06-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_artista_playlist_alter_concierto_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recinto',
            name='idRecinto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='idRecinto'),
        ),
    ]
