# Generated by Django 4.2.1 on 2023-06-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_delete_pais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artista',
            options={'ordering': ['nomArtista', 'genero'], 'verbose_name': 'Artista', 'verbose_name_plural': 'Artistas'},
        ),
        migrations.RemoveField(
            model_name='artista',
            name='show',
        ),
        migrations.RemoveField(
            model_name='concierto',
            name='pais',
        ),
        migrations.AddField(
            model_name='artista',
            name='genero',
            field=models.CharField(max_length=70, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='anio',
            field=models.CharField(max_length=4, verbose_name='Año de formación'),
        ),
        migrations.AlterField(
            model_name='concierto',
            name='fecha',
            field=models.DateTimeField(max_length=60, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='concierto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='concierto', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='concierto',
            name='valores',
            field=models.IntegerField(verbose_name='Entradas desde'),
        ),
    ]
