# Generated by Django 4.2.1 on 2023-06-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_artista_options_remove_artista_show_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierto',
            name='valores',
            field=models.CharField(max_length=500, verbose_name='Entradas desde'),
        ),
    ]
