# Generated by Django 4.2.1 on 2023-06-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_recinto_idrecinto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='idArtista',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='idArtista'),
        ),
    ]
