# Generated by Django 4.2.1 on 2023-06-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_alter_artista_idartista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierto',
            name='fecha',
            field=models.DateTimeField(default='28.06.2023 01:55:08', max_length=60, verbose_name='Fecha'),
        ),
    ]
